<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AWSSDK.S3" Version="4.0.7.7" />
    <PackageReference Include="OutSystems.ExternalLibraries.SDK" Version="1.5.0" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="8.0.0" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="resources/S3Orchestrator_ExternalLogic_lib.png" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="resources/qpdf/qpdf-12.3.0-bin-linux-x86_64.zip">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Version1_06.cs" />
  </ItemGroup>

</Project>
